input {
  file {
    path => "/usr/share/logstash/ingest_data/sample_logs.json"
    start_position => "beginning"
    sincedb_path => "/dev/null" # This forces it to re-read the file every time we restart for testing
    codec => "json"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "arch-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } # This lets us see the progress in the terminal
}
